config:
  clients:
    - url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push

  # This merges into all existing scrape jobs
  snippets:
    extraRelabelConfigs:
      # Drop logs from the 'loki' namespace
      - source_labels: ['__meta_kubernetes_namespace']
        regex: 'kube-system|grafana|kube-node-lease|kube-public|loki'
        action: drop
